### ISSUE TITLE
Revolution R 3.2.3 on mac

### ISSUE THREAD

**Issue by noblehendrix** [James-Thorson/2016_Spatio-temporal_models#1]
Hi there,

I though that I would get the comments list started.

Just a heads up for those Mac users who may want to try Revolution R, which is now Microsoft Open R.  Apparently version 3.2.3 is having some issues with the clang compiler and will throw errors when you try to compile your TMB file.   The most recent of R via CRAN (Version 3.2.4) seems to work just fine, so it appears to be an issue with the Microsoft Open R on a Mac - go figure!

Noble

**Comment by bethphillips** [comment]
Hi Noble -

Thanks for this.  So...I was able to compile with R 3.2.4 on Mac OS in the Lecture 1 code (e.g., compile ("linear_model_v1.cpp" )) but am getting a bunch of errors when I try to compile the Lab 1 code (compile( "delta_model_v1.cpp" )).  Anyone else having this issue, or is it just me?

Thanks,
beth

P.S. here's my error message(s) FWIW

> compile( "delta_model_v1.cpp" )
Note: Using Makevars in /Users/elizabeth/.R/Makevars 
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include -I/Library/Frameworks/R.framework/Versions/3.2/Resources/library/RcppEigen/include -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_delta_model_v1  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c delta_model_v1.cpp -o delta_model_v1.o
delta_model_v1.cpp:6:17: error: call to function 'dnorm' that is neither visible in the template definition nor found by argument-dependent lookup
  Type logres = dnorm( log(x), meanlog, sdlog, true) - log(x);
                ^
delta_model_v1.cpp:36:48: note: in instantiation of function template specialization 'dlognorm<CppAD::AD<double> >' requested here
    if(y_i(i)!=0) jnll -= log( 1-zero_prob ) + dlognorm( y_i(i), linpred_i(i), logsd, true );
                                               ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/tmb_core.hpp:934:6: note: in instantiation of member function 'objective_function<CppAD::AD<double> >::operator()' requested here
    F(); // Run through user template (modifies reportvector)
     ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/dnorm.hpp:9:6: note: 'dnorm' should be declared prior to the call site or in namespace 'CppAD'
Type dnorm(Type x, Type mean, Type sd, int give_log=0)
     ^
delta_model_v1.cpp:6:24: error: call to function 'log' that is neither visible in the template definition nor found by argument-dependent lookup
  Type logres = dnorm( log(x), meanlog, sdlog, true) - log(x);
                       ^
delta_model_v1.cpp:36:48: note: in instantiation of function template specialization 'dlognorm<double>' requested here
    if(y_i(i)!=0) jnll -= log( 1-zero_prob ) + dlognorm( y_i(i), linpred_i(i), logsd, true );
                                               ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/tmb_core.hpp:1153:25: note: in instantiation of member function 'objective_function<double>::operator()' requested here
      res = asSEXP( pf->operator()() );
                        ^
/usr/include/math.h:387:15: note: 'log' should be declared prior to the call site
extern double log(double);
              ^
delta_model_v1.cpp:6:17: error: call to function 'dnorm' that is neither visible in the template definition nor found by argument-dependent lookup
  Type logres = dnorm( log(x), meanlog, sdlog, true) - log(x);
                ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/dnorm.hpp:9:6: note: 'dnorm' should be declared prior to the call site
Type dnorm(Type x, Type mean, Type sd, int give_log=0)
     ^
delta_model_v1.cpp:6:56: error: call to function 'log' that is neither visible in the template definition nor found by argument-dependent lookup
  Type logres = dnorm( log(x), meanlog, sdlog, true) - log(x);
                                                       ^
/usr/include/math.h:387:15: note: 'log' should be declared prior to the call site
extern double log(double);
              ^
delta_model_v1.cpp:7:43: error: call to function 'exp' that is neither visible in the template definition nor found by argument-dependent lookup
  if(give_log) return logres; else return exp(logres);
                                          ^
/usr/include/math.h:375:15: note: 'exp' should be declared prior to the call site
extern double exp(double);
              ^
delta_model_v1.cpp:6:17: error: call to function 'dnorm' that is neither visible in the template definition nor found by argument-dependent lookup
  Type logres = dnorm( log(x), meanlog, sdlog, true) - log(x);
                ^
delta_model_v1.cpp:36:48: note: in instantiation of function template specialization 'dlognorm<CppAD::AD<CppAD::AD<double> > >' requested here
    if(y_i(i)!=0) jnll -= log( 1-zero_prob ) + dlognorm( y_i(i), linpred_i(i), logsd, true );
                                               ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/tmb_core.hpp:701:20: note: in instantiation of member function 'objective_function<CppAD::AD<CppAD::AD<double> > >::operator()' requested here
    Type ans=this->operator()();
                   ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/tmb_core.hpp:1192:10: note: in instantiation of member function 'objective_function<CppAD::AD<CppAD::AD<double> > >::evalUserTemplate' requested here
  y[0]=F.evalUserTemplate();
         ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/dnorm.hpp:9:6: note: 'dnorm' should be declared prior to the call site or in namespace 'CppAD'
Type dnorm(Type x, Type mean, Type sd, int give_log=0)
     ^
delta_model_v1.cpp:6:17: error: call to function 'dnorm' that is neither visible in the template definition nor found by argument-dependent lookup
  Type logres = dnorm( log(x), meanlog, sdlog, true) - log(x);
                ^
delta_model_v1.cpp:36:48: note: in instantiation of function template specialization 'dlognorm<CppAD::AD<CppAD::AD<CppAD::AD<double> > > >' requested here
    if(y_i(i)!=0) jnll -= log( 1-zero_prob ) + dlognorm( y_i(i), linpred_i(i), logsd, true );
                                               ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/tmb_core.hpp:701:20: note: in instantiation of member function 'objective_function<CppAD::AD<CppAD::AD<CppAD::AD<double> > > >::operator()' requested here
    Type ans=this->operator()();
                   ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/tmb_core.hpp:1307:12: note: in instantiation of member function 'objective_function<CppAD::AD<CppAD::AD<CppAD::AD<double> > > >::evalUserTemplate' requested here
  y[0] = F.evalUserTemplate();
           ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/dnorm.hpp:9:6: note: 'dnorm' should be declared prior to the call site or in namespace 'CppAD'
Type dnorm(Type x, Type mean, Type sd, int give_log=0)
     ^
7 errors generated.
make: *** [delta_model_v1.o] Error 1
Error in compile("delta_model_v1.cpp") : Compilation failed
>

**Comment by James-Thorson** [comment]
Try putting the #include TMB line at the top of the CPP file -- Neal and Jin both found that it needed to be at the top for the compiler on a Mac.
